class TestData:
    Chrome_Executable_Path = "/Users/asusmitha/Desktop/chromedriver.exe"

    Base_Url = "https://hashedinhire-frontend-urtjok3rza-wl.a.run.app/login"
    InterviewerUserName = "susmitha@gmail.com"
    RecruiterUsername = 'srilakshmi@gmail.com'
    CandidateUsername = 'girish@gmail.com'
    Password = "Password@123"
    LoginPageTitle = "Hashedin Hire"
    ZoomPageTitle = "Launch Meeting - Zoom"
    ExpectedValue = True
    Role_In = 'Python Developer'
    Skill1 = 'Python'
    Skill2 = 'Django'
    Skill3 = 'React'
    Min_data = '2'
    Max_data = '5'
    Res_Data = 'Building web applications'
    Upload_file = 'C:/Users/visrilakshmi/Downloads/API Track Main Assignment Day 2.docx'
    Alert_msg = 'Job has been Created!'
    created_job = 'Unable to create new job'
    Error_msg = 'Candidates are not available'
    Error_msg2 = 'Candidates not available'
    int_comp = 'Interview is completed'
    no_fed = 'No candidates available to give feedback'
    search_job = 'SDET2'
    InterviewerErrorMessage = 'Failed to login and display the buttons'
    JobopeningsErrorMessage = 'Failed to validate Job Openings Page'
    DashboardErrorMessage = 'Failed to validate Dahsboard'
    ProfilePageErrorMessage = 'Failed to validate Profile page'
    InterviewRequestsErrorMessage = 'Failed to perform  actions accept, reject and reschedule'
